### ISSUE TITLE
Uncaught Error: Class 'ipl\Sql\Select' not found

### ISSUE THREAD

**Issue by lipazsolt** [Icinga/icingaweb2-module-ipl#2]
Hi! 

Please change the version number in the README markdown file.
If I use `v0.2.0` I've got an `Uncaught Error`, but when I switch to `v0.2.1` it works perfectly. :)

Workaround:
`me@icinga:/usr/share/icingaweb2/modules/ipl$ sudo git checkout v0.2.1`

Thanks for this amazing tools! 🏆 😄

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this!
