### ISSUE TITLE
Persistent message "Please install a Release version of the IPL module, not the GIT master"

### ISSUE THREAD

**Issue by Tontonitch** [Icinga/icingaweb2-module-ipl#3]
Hello,

I'm using the last release tar archive, but still facing the warning message.

![image](https://user-images.githubusercontent.com/600025/57066295-20be9580-6ccc-11e9-8904-24ec4eb87f1c.png)

**Comment by Thomas-Gelf** [comment]
@Tontonitch: could you please double-check this? Symlinks in `enabledModules` pointing to the right directory, module directory name being `ipl` and not `icingaweb2-module-ipl`...?

**Comment by Tontonitch** [comment]
What I did:
```
[root@monitorsrv1 tmp]# MODULE_NAME=ipl
[root@monitorsrv1 tmp]# MODULE_VERSION=v0.2.1
[root@monitorsrv1 tmp]# MODULES_PATH="/usr/share/icingaweb2/modules"
[root@monitorsrv1 tmp]# MODULE_PATH="${MODULES_PATH}/${MODULE_NAME}"
[root@monitorsrv1 tmp]# RELEASES="https://github.com/Icinga/icingaweb2-module-${MODULE_NAME}/archive"
[root@monitorsrv1 tmp]# icingacli module disable "${MODULE_NAME}"
[root@monitorsrv1 tmp]# mv $MODULE_PATH ${MODULE_PATH}_20190502_2
[root@monitorsrv1 tmp]# ls -larth $MODULE_PATH
ls: cannot access /usr/share/icingaweb2/modules/ipl: No such file or directory
[root@monitorsrv1 tmp]# mkdir "$MODULE_PATH" \
>  && wget -q $RELEASES/${MODULE_VERSION}.tar.gz -O - \
>     | tar xfz - -C "$MODULE_PATH" --strip-components 1
[root@monitorsrv1 tmp]# ls -larth $MODULE_PATH
total 24K
drwxrwxr-x   8 root root  109 Mar 26 20:32 vendor
-rw-rw-r--   1 root root   54 Mar 26 20:32 run.php
-rw-rw-r--   1 root root 1.3K Mar 26 20:32 README.md
-rw-rw-r--   1 root root  209 Mar 26 20:32 module.info
-rw-rw-r--   1 root root   41 Mar 26 20:32 .gitignore
-rw-rw-r--   1 root root  581 Mar 26 20:32 composer.json
drwxrwxr-x   2 root root   28 Mar 26 20:32 bin
drwxr-xr-x. 45 root root 4.0K May  2 11:57 ..
drwxr-xr-x   4 root root  114 May  2 11:57 .
[root@monitorsrv1 tmp]# icingacli module enable "${MODULE_NAME}"
[root@monitorsrv1 tmp]#
```
I still see the message in icingaweb2 after refreshing the page.

**Comment by Thomas-Gelf** [comment]
Looks good to me, should work this way... strange

**Comment by kevin-olbrich** [comment]
I am facing the same problem with stable/0.3.0.
I've checked out the repo and switched over to "stable/0.3.0"-branch as stated in the docs (git checkout stable/0.3.0).
I am using the x509 module and it seems to work. A quick search did not show up which condition is making your module think, I am using master.

**Comment by Tontonitch** [comment]
I've found why the problem occurred.
I had another module, pdfexport, which apparently what created using parts of the IPL module and having at least the same description. I've updated pdfexport to a newer version and I don't have the message anymore. You may close the issue.

![image](https://user-images.githubusercontent.com/600025/68392720-af740980-016a-11ea-9265-4b877b6d0cc2.png)

**Comment by buggsdummy** [comment]
This issue is still not resolved. I am getting this error too.

**Comment by buggsdummy** [comment]
Install the zip version of the branch
