### ISSUE TITLE
Module not functional with SSL

### ISSUE THREAD

**Issue by maelig** [Icinga/icingaweb2-module-ipl#4]
Hello,

The use of SSL options does not work with the IPL module. Must miss PDO parameter :: MYSQL_ATTR_SSL_CA ?

Modules version :
* ipl => v0.3.0
* reporting => 0.9.2
* idoreports => 0.9.1

![Resources  Icinga Web - Google Chrome](https://user-images.githubusercontent.com/7013790/63783609-97bc1180-c8ed-11e9-8b95-3033faa08b0c.png)
![Reporting  Icinga Web - Google Chrome](https://user-images.githubusercontent.com/7013790/63783612-97bc1180-c8ed-11e9-8a5b-5406ab351f59.jpg)

**Comment by lippserd** [comment]
Since Icinga/ipl-sql#11 has been merged and released, this should now work.
