### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by Prathameshhankare** [Icinga/icingaweb2-module-ipl#9]
My Icingaweb2 response is very slow. I found some application log recently as below.

![image](https://user-images.githubusercontent.com/52577680/87806870-24105380-c875-11ea-81ba-04686a55c05a.png)

Please look into it and help me out.

**Comment by lippserd** [comment]
Hi @Prathameshhankare,

Which version of `ipl` are you using and which view exceeds the allowed memory size?

You may of course increase PHP's memory limit.

Best regards,
Eric
